version: '3'
services:

  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - grafana-prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - grafana-prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  prometheus-data:
  grafana-data:

networks:
  grafana-prometheus:
    driver: bridge
